In [0]:
import torch

Matrix transpose

In [1]:
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->ji', [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [10]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

Sum

In [4]:
torch.einsum('ij->', [a])

tensor(15)

Sum by axis

In [7]:
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

Matrix-vector multiplication

In [12]:
b = torch.arange(3)
b

tensor([0, 1, 2])

In [13]:
torch.einsum('ij,j->i', [a, b])

tensor([ 5, 14])

In [14]:
a @ b

tensor([ 5, 14])

Matrix-Matrix multiplication

In [16]:
c = torch.arange(15).reshape(3, 5)
c

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [17]:
c.shape

torch.Size([3, 5])

In [18]:
a.shape

torch.Size([2, 3])

In [19]:
torch.einsum('ik,kj->ij', [a, c])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [21]:
a @ c

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

Dot product

In [23]:
a = torch.arange(3)
b = torch.arange(3, 6)
torch.einsum('i,i->', [a, b])

tensor(14)

In [24]:
a @ b

tensor(14)

HADAMARD product

In [25]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->ij', [a, b])

tensor([[ 0,  7, 16],
        [27, 40, 55]])

Batch Matrix Multiplication

In [26]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
torch.einsum('ijk,ikl->ijl', [a, b])

tensor([[[ 0.8891,  1.2693, -0.1136],
         [ 0.3476,  4.1269, -1.4629]],

        [[ 0.3086,  2.0349, -3.6681],
         [-0.5799, -2.5252,  2.7563]],

        [[ 0.2753, -4.5057, -4.2450],
         [ 1.1568, -4.0025, -3.1627]]])

Tensor Contraction

In [27]:
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape

torch.Size([2, 7, 11, 13, 17])

In [28]:
a = torch.arange(6)

In [29]:
a

tensor([0, 1, 2, 3, 4, 5])

In [37]:
torch.einsum('i,j->ij', [a, a])

tensor([[ 0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5],
        [ 0,  2,  4,  6,  8, 10],
        [ 0,  3,  6,  9, 12, 15],
        [ 0,  4,  8, 12, 16, 20],
        [ 0,  5, 10, 15, 20, 25]])